packageExtensions:
  "@parcel/config-default@*":
    dependencies:
      "@babel/core": "*"
      postcss: "*"
  "@parcel/optimizer-image@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/transformer-image@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/transformer-js@*":
    dependencies:
      "@parcel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
